import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { PrismaClient } from "../app/generated/prisma/client";

const prisma = new PrismaClient();

// memaksa Next.js untuk selalu mengambil data terbaru dari database (bukan static cache)
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Website Biodata",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ambil setting dari database
  const settings = await prisma.siteSetting.findUnique({
    where: { id: "global" },
  });

  // nilai default if database empty
  const bg = settings?.background || "#ffffff";
  const color = settings?.textColor || "#000000";
  const font = settings?.fontFamily || "sans-serif";

  return (
    <html lang="en">
      {/* terapkan style secara global di tag body */}
      <body 
        style={{ 
          backgroundColor: bg, 
          color: color, 
          fontFamily: font,
          minHeight: "100vh",
          transition: "all 0.3s ease" // animasi
        }}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}